#!/bin/bash

# Project available at github.com/olback/bash_aliases

# Create date variable
d="$(date +%F)"

# Rename the old .bash_aliases to .bash_aliases.<current date>.
mv ~/.bash_aliases ~/.bash_aliases.$d

# Download new version from https://raw.githubusercontent.com/olback/bash_aliases/master/bash_aliases
wget https://raw.githubusercontent.com/olback/bash_aliases/master/bash_aliases --https-only -O ~/.bash_aliases

# Colors, why not?
COLOR='\033[1;32m'
NC='\033[0m'

# Print Done!
printf "${COLOR}Done!${NC} \n\n"
printf 'Run ". ~/.bash_aliases" or open a new terminal to use your aliases.\n\n'
