#!/bin/sh

echo 'Creating dirs...'
mkdir css
mkdir js
mkdir img
mkdir res

echo 'Creating some files...'
touch index.php
touch 40x.php
touch res/head.php
touch res/footer.php
touch css/main.css
touch js/main.js

echo 'Writing to files...'
echo 'Writing to index.php...'
echo '<?php include __DIR__."/res/head.php";?>' > index.php
echo '<h1>Generated by olbacks web-init script</h1>' >> index.php
echo '<?php include __DIR__."/res/footer.php";?>' >> index.php

echo 'Writing to 40x.php'
echo '<?php include __DIR__."/res/head.php";?>' > 40x.php
echo '<h1>404 - Page not found</h1>' >> 40x.php
echo '<?php include __DIR__."/res/footer.php";?>' >> 40x.php

echo 'Writing to res/head.php...'
echo '<!DOCTYPE html>' > res/head.php
echo '<html lang="en">' >> res/head.php
echo '	<head>' >> res/head.php
echo '		<title>Title</title>' >> res/head.php
echo ' 		<meta charset="UTF-8">' >> res/head.php
echo '      <link rel="stylesheet" type="text/css" href="css/main.css">' >> res/head.php
echo '		<script src="js/main.js"></script>' >> res/head.php
echo '	</head>' >> res/head.php
echo '	<body>' >> res/head.php

echo 'Writing to res/footer.php'
echo '	</body>' > res/footer.php
echo '</html>' >> res/footer.php

echo 'Writing to css/main.css...'
echo 'h1 {text-align: center;}' >> css/main.css

echo 'Writing to js/main.js'
echo 'console.log("Main.js loaded");' >> js/main.js

echo 'Done!'
