[defaults]
notification-cmd = "notify-send -i email 'New mail' '{name}'"
folder = "INBOX"
trim-password = true

['@olback.net']
address = "mail.olback.net"
port = 993
username = "olback@olback.net"
password-cmd = "gnome-keyring-query get mail_olback_net"
#folder = "INBOX" # Defaults to "INBOX"
#trim-password = true
#notification-cmd = ""

['@gmail.com']
address = "imap.gmail.com"
port = 993
username = "edwinsvensson@gmail.com"
password-cmd = "gnome-keyring-query get mail_gmail_com"

['@student.hh.se']
address = "outlook.office365.com"
port = 993
username = "edwsve19@student.hh.se"
password-cmd = "gnome-keyring-query get mail_hh_se"

